/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* f_bu:(i0[6])->(o0[6],o1[6],o2[6],o3[6],o4[6],o5[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=-3.9873781047649871e+01;
  if (res[0]!=0) res[0][0]=a0;
  a1=-3.3425691614686393e+01;
  if (res[0]!=0) res[0][1]=a1;
  a2=-2.4755515136307189e+01;
  if (res[0]!=0) res[0][2]=a2;
  a3=-9.4185787661365566e+01;
  if (res[0]!=0) res[0][3]=a3;
  a4=1.7585800777619849e+02;
  if (res[0]!=0) res[0][4]=a4;
  a5=-5.0039650510261211e+01;
  if (res[0]!=0) res[0][5]=a5;
  a6=-1.2246467991473532e-16;
  a7=arg[0]? arg[0][0] : 0;
  a8=sin(a7);
  a9=(a6*a8);
  a7=cos(a7);
  a9=(a9-a7);
  a9=(a0*a9);
  a10=1.2246467991473532e-16;
  a11=(a10*a7);
  a11=(a11-a8);
  a11=(a1*a11);
  a9=(a9+a11);
  if (res[1]!=0) res[1][0]=a9;
  a11=(a6*a7);
  a11=(a8+a11);
  a11=(a0*a11);
  a12=(a10*a8);
  a12=(a12+a7);
  a12=(a1*a12);
  a11=(a11-a12);
  if (res[1]!=0) res[1][1]=a11;
  if (res[1]!=0) res[1][2]=a2;
  a12=1.6250000000000001e-01;
  a13=(a12*a8);
  a14=-1.6250000000000001e-01;
  a15=(a14*a7);
  a16=(a6*a15);
  a16=(a13-a16);
  a16=(a0*a16);
  a13=(a10*a13);
  a15=(a15-a13);
  a15=(a1*a15);
  a16=(a16+a15);
  a15=(a6*a8);
  a15=(a15-a7);
  a15=(a3*a15);
  a16=(a16+a15);
  a15=(a10*a7);
  a15=(a15-a8);
  a15=(a4*a15);
  a16=(a16+a15);
  if (res[1]!=0) res[1][3]=a16;
  a12=(a12*a7);
  a14=(a14*a8);
  a15=(a6*a14);
  a15=(a12+a15);
  a0=(a0*a15);
  a12=(a10*a12);
  a12=(a12+a14);
  a1=(a1*a12);
  a0=(a0-a1);
  a6=(a6*a7);
  a6=(a8+a6);
  a3=(a3*a6);
  a0=(a0+a3);
  a10=(a10*a8);
  a10=(a10+a7);
  a4=(a4*a10);
  a0=(a0-a4);
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a5;
  a4=arg[0]? arg[0][1] : 0;
  a10=cos(a4);
  a7=(a10*a9);
  a8=-2.0510342851533115e-10;
  a4=sin(a4);
  a3=(a8*a4);
  a6=(a3*a11);
  a7=(a7+a6);
  a6=(a2*a4);
  a7=(a7+a6);
  if (res[2]!=0) res[2][0]=a7;
  a6=(a8*a10);
  a1=(a6*a11);
  a9=(a4*a9);
  a1=(a1-a9);
  a2=(a2*a10);
  a1=(a1+a2);
  if (res[2]!=0) res[2][1]=a1;
  a2=5.0774410291197798e-09;
  a2=(a2-a11);
  if (res[2]!=0) res[2][2]=a2;
  a11=(a10*a16);
  a3=(a3*a0);
  a11=(a11+a3);
  a3=(a5*a4);
  a11=(a11+a3);
  if (res[2]!=0) res[2][3]=a11;
  a6=(a6*a0);
  a4=(a4*a16);
  a6=(a6-a4);
  a5=(a5*a10);
  a6=(a6+a5);
  if (res[2]!=0) res[2][4]=a6;
  a5=1.0263303881363515e-08;
  a5=(a5-a0);
  if (res[2]!=0) res[2][5]=a5;
  a0=arg[0]? arg[0][2] : 0;
  a10=cos(a0);
  a4=(a10*a7);
  a0=sin(a0);
  a16=(a0*a1);
  a4=(a4+a16);
  if (res[3]!=0) res[3][0]=a4;
  a16=(a10*a1);
  a7=(a0*a7);
  a16=(a16-a7);
  if (res[3]!=0) res[3][1]=a16;
  if (res[3]!=0) res[3][2]=a2;
  a7=(a10*a11);
  a3=4.2499999999999999e-01;
  a9=(a3*a0);
  a9=(a9*a2);
  a7=(a7-a9);
  a9=(a0*a6);
  a7=(a7+a9);
  if (res[3]!=0) res[3][3]=a7;
  a6=(a10*a6);
  a10=(a3*a10);
  a10=(a10*a2);
  a0=(a0*a11);
  a10=(a10+a0);
  a6=(a6-a10);
  if (res[3]!=0) res[3][4]=a6;
  a3=(a3*a1);
  a3=(a3+a5);
  if (res[3]!=0) res[3][5]=a3;
  a5=arg[0]? arg[0][3] : 0;
  a1=cos(a5);
  a10=(a1*a4);
  a5=sin(a5);
  a0=(a5*a16);
  a10=(a10+a0);
  if (res[4]!=0) res[4][0]=a10;
  a0=(a1*a16);
  a11=(a5*a4);
  a0=(a0-a11);
  if (res[4]!=0) res[4][1]=a0;
  if (res[4]!=0) res[4][2]=a2;
  a11=(a1*a7);
  a9=1.3330000000000000e-01;
  a12=(a9*a5);
  a12=(a12*a4);
  a14=-1.3330000000000000e-01;
  a15=(a14*a1);
  a15=(a15*a16);
  a12=(a12+a15);
  a15=3.9219999999999999e-01;
  a13=(a15*a5);
  a13=(a13*a2);
  a12=(a12+a13);
  a11=(a11-a12);
  a12=(a5*a6);
  a11=(a11+a12);
  if (res[4]!=0) res[4][3]=a11;
  a14=(a14*a5);
  a14=(a14*a16);
  a9=(a9*a1);
  a9=(a9*a4);
  a14=(a14-a9);
  a9=(a15*a1);
  a9=(a9*a2);
  a14=(a14-a9);
  a5=(a5*a7);
  a14=(a14-a5);
  a1=(a1*a6);
  a14=(a14+a1);
  if (res[4]!=0) res[4][4]=a14;
  a15=(a15*a16);
  a15=(a15+a3);
  if (res[4]!=0) res[4][5]=a15;
  a3=arg[0]? arg[0][4] : 0;
  a16=cos(a3);
  a1=(a16*a10);
  a3=sin(a3);
  a6=(a8*a3);
  a5=(a6*a0);
  a1=(a1+a5);
  a5=(a3*a2);
  a1=(a1+a5);
  if (res[5]!=0) res[5][0]=a1;
  a1=(a8*a16);
  a5=(a1*a0);
  a7=(a3*a10);
  a5=(a5-a7);
  a7=(a16*a2);
  a5=(a5+a7);
  if (res[5]!=0) res[5][1]=a5;
  a5=(a8*a2);
  a5=(a5-a0);
  if (res[5]!=0) res[5][2]=a5;
  a5=(a16*a11);
  a7=-2.0448811822978519e-11;
  a9=(a7*a6);
  a4=9.9699999999999997e-02;
  a12=(a4*a3);
  a9=(a9+a12);
  a9=(a9*a10);
  a12=2.0448811822978519e-11;
  a13=(a12*a16);
  a13=(a13*a0);
  a9=(a9+a13);
  a13=-9.9699999999999997e-02;
  a17=(a13*a16);
  a17=(a17*a2);
  a9=(a9+a17);
  a5=(a5-a9);
  a6=(a6*a14);
  a5=(a5+a6);
  a6=(a3*a15);
  a5=(a5+a6);
  if (res[5]!=0) res[5][3]=a5;
  a12=(a12*a3);
  a12=(a12*a0);
  a7=(a7*a1);
  a4=(a4*a16);
  a7=(a7+a4);
  a7=(a7*a10);
  a12=(a12-a7);
  a13=(a13*a3);
  a13=(a13*a2);
  a12=(a12+a13);
  a3=(a3*a11);
  a12=(a12-a3);
  a1=(a1*a14);
  a12=(a12+a1);
  a16=(a16*a15);
  a12=(a12+a16);
  if (res[5]!=0) res[5][4]=a12;
  a12=-3.2311742677852644e-27;
  a12=(a12*a10);
  a12=(a12-a14);
  a8=(a8*a15);
  a12=(a12+a8);
  if (res[5]!=0) res[5][5]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_bu(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_bu_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_bu_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_bu_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_bu_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_bu_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_bu_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_bu_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_bu_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int f_bu_n_out(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_real f_bu_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_bu_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_bu_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    case 5: return "o5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_bu_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_bu_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_bu_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
