# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vicon_data_publisher/Marker_global_translation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Marker_global_translation(genpy.Message):
  _md5sum = "5c777987c5408d004a4cb26c1b32959e"
  _type = "vicon_data_publisher/Marker_global_translation"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 frameNumber
byte markerNumber
bool occluded
float64 x_m
float64 y_m
float64 z_m
"""
  __slots__ = ['frameNumber','markerNumber','occluded','x_m','y_m','z_m']
  _slot_types = ['uint32','byte','bool','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frameNumber,markerNumber,occluded,x_m,y_m,z_m

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Marker_global_translation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.frameNumber is None:
        self.frameNumber = 0
      if self.markerNumber is None:
        self.markerNumber = 0
      if self.occluded is None:
        self.occluded = False
      if self.x_m is None:
        self.x_m = 0.
      if self.y_m is None:
        self.y_m = 0.
      if self.z_m is None:
        self.z_m = 0.
    else:
      self.frameNumber = 0
      self.markerNumber = 0
      self.occluded = False
      self.x_m = 0.
      self.y_m = 0.
      self.z_m = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_IbB3d().pack(_x.frameNumber, _x.markerNumber, _x.occluded, _x.x_m, _x.y_m, _x.z_m))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 30
      (_x.frameNumber, _x.markerNumber, _x.occluded, _x.x_m, _x.y_m, _x.z_m,) = _get_struct_IbB3d().unpack(str[start:end])
      self.occluded = bool(self.occluded)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_IbB3d().pack(_x.frameNumber, _x.markerNumber, _x.occluded, _x.x_m, _x.y_m, _x.z_m))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 30
      (_x.frameNumber, _x.markerNumber, _x.occluded, _x.x_m, _x.y_m, _x.z_m,) = _get_struct_IbB3d().unpack(str[start:end])
      self.occluded = bool(self.occluded)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IbB3d = None
def _get_struct_IbB3d():
    global _struct_IbB3d
    if _struct_IbB3d is None:
        _struct_IbB3d = struct.Struct("<IbB3d")
    return _struct_IbB3d
